# Usar la imagen oficial de Node.js como base
FROM node:22.11.0

# Crear un directorio de trabajo en el contenedor
WORKDIR /app

# Copiar package.json y package-lock.json
COPY package*.json ./

# Instalar las dependencias del proyecto
RUN npm install

# Copiar el código del frontend al contenedor
COPY . .

# Exponer el puerto 5173 (puerto por defecto de Vite en modo desarrollo)
EXPOSE 5173

# Comando para ejecutar la aplicación en modo de desarrollo
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
