

services:
  backend:
    build:
      context: ./backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    networks:
      - mynetwork

  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"  
    depends_on:
      - backend
    networks:
      - mynetwork
    command: npm run dev -- --host 0.0.0.0

networks:
  mynetwork:
    driver: bridge
