# Utilizar una imagen base de Node.js
FROM node:22.11.0

# Establecer el directorio de trabajo en el contenedor
WORKDIR /app

# Copiar el archivo package.json y package-lock.json
COPY ./package*.json ./

# Instalar las dependencias
RUN npm install

# Copiar todo el código del backend al contenedor
COPY . .

# Exponer el puerto en el que el backend escuchará
EXPOSE 3000

# Comando para iniciar la aplicación
CMD ["npm", "start"]
